server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/video?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: Test_123
    driver-class-name: com.mysql.cj.jdbc.Driver
